### ISSUE TITLE
npm ERR! peerinvalid  - The package handlebars does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by prabackar** [toranb/ember-template-compiler#22]
After the last commit, I am running into peerinvalid issue!

npm ERR! peerinvalid The package handlebars does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ember-template-compiler@1.9.0-alpha wants handlebars@~2

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "handlebars"
npm ERR! cwd /Users/pkasi/Documents/environment/........
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pkasi/Documents/environment/..../npm-debug.log
npm ERR! not ok code 0

I updated bower config but I am unable to get past this error....

**Comment by NullVoxPopuli** [comment]
which version of ember-template-compiler fixes this? I have this same problem. (package.json specifies 1.9.0-alpha)

**Comment by NullVoxPopuli** [comment]
`npm ERR! peerinvalid Peer ember-template-compiler@1.8.0 wants handlebars@~1`

```
npm ERR! peerinvalid The package handlebars does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ember-template-compiler@1.7.0 wants handlebars@~1
```

```
npm ERR! peerinvalid The package handlebars does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ember-template-compiler@1.6.1 wants handlebars@~1
```

these are with with `"handlebars": "4.0.5",` also specified in my package.json

If I downgrade handlebars waaaay down, it works.

```
    "ember-template-compiler": "^1.8.0",
    "handlebars": "^1.3.0",
```

I like to keep things up to date, so I'm not sure if this is a good long term solution.

**Comment by Jarred-Sumner** [comment]
Happening to me, too.

**Comment by jakeleboeuf** [comment]
uuuhhhh

**Comment by toranb** [comment]
@rwjblue is the solution here to end of life this and tell users to fork it if needed??

**Comment by rwjblue** [comment]
Yes

**Comment by toranb** [comment]
@NullVoxPopuli I realize the hbs v1.3.0 solution isn't something you were excited about but it may be worth publishing something that forks this like Robert suggests. Also if I may ask - what is everyone using that isn't ember-cli right now? Are most of you planning to upgrade/adopt ember-cli at some point in time this year?

**Comment by Jarred-Sumner** [comment]
Is this only a problem when not using ember-cli? I'm using ember-cli and
this error occurs

**Comment by toranb** [comment]
@Jarred-Sumner what version of ember-cli are you using? what version of ember?
