### ISSUE TITLE
Error: Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by jcope2013** [toranb/ember-template-compiler#29]
```
ember serve
Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/JoshuaCope/Desktop/InboxDashboard/node_modules/ember-cli-htmlbars/node_modules/ember-template-compiler/vendor/ember-template-compiler.js:29:16
    at Object.<anonymous> (/Users/JoshuaCope/Desktop/InboxDashboard/node_modules/ember-cli-htmlbars/node_modules/ember-template-compiler/vendor/ember-template-compiler.js:290:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

related to this

https://github.com/toranb/ember-template-compiler/commit/b924608fb9652850d6e297b61b9bd116fe157faa

I am on ember cli 0.2.0, ember 1.9.1, handlebars 2.0 and ember-cli-htmlbars 0.6.0 and now i cant run ember serve or build my app

i have to add 

ember-template-compiler": "1.9.0-alpha", in my package.json

**Comment by toranb** [comment]
Honestly this sounds like I should unpublish the latest build of 1.9.1 (as I removed the peer deps). @rwjblue can you confirm publishing that was a terrible idea?

**Comment by toranb** [comment]
I went ahead and did the unpublish as this will break everyone using ember-cli at the moment. Can you npm cache clean and npm install again (removing the hard coded 1.9.0-alpha line you added earlier) ?

**Comment by jcope2013** [comment]
yeah that worked, thanks for the quick action

**Comment by toranb** [comment]
sorry for the world ending publish :( honestly afraid to update this module w/out some help and or guidance from the core team (as everything seems to be standing on this module for ember-cli)

**Comment by rwjblue** [comment]
@toranb - We have moved ember-cli to use ember-cli-htmlbars and the template compiler shipped directly with the specific ember build being used in 0.2.0 so as folks update, this module will slowly be used less and less....
