### ISSUE TITLE
[Question] Deprecated or is ember still using this in their build process?

### ISSUE THREAD

**Issue by ghost** [toranb/ember-template-compiler#31]
Is this module deprecated or is ember still using this in their build process? :sweat_smile:

**Comment by toranb** [comment]
I believe HTMLBars essentially replaced this in ember 1.9 or 1.10+

**Comment by bucaran** [comment]
@toranb Oh, I see. Should I interpret this response as look somewhere else if you want to build an ember app without `ember-cli` the answer is not here? :laughing: 

Thanks!

**Comment by rwjblue** [comment]
http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html

**Comment by ghost** [comment]
@rwjblue Thanks.

**Comment by rwjblue** [comment]
Rolling a custom build process sounds like great job security!

**Comment by toranb** [comment]
haha don't take @rwjblue too seriously :) but he has a good point. If you just want to learn here is a gulp build I wrote/maintained before ember-cli took off. It's not current and won't work with anything ember 1.9+ but if you want to hack on this with ember 1.8.1 you should learn a few things anyway.

https://github.com/toranb/ember-gulp-example/blob/master/Gulpfile.js

**Comment by ghost** [comment]
@rwjblue :smile:
@toranb Thanks! :+1:
